<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>DvMod.RemoteDispatch</RootNamespace>
    <InformationalVersion>1.4.3</InformationalVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\node_modules\**;tests\**\bin\**;tests\**\obj\**;Multiplayer\bin\**;Multiplayer\obj\**;dist\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1"/>
    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp"/>
    <Reference Include="DV.BrakeSystem"/>
    <Reference Include="DV.Simulation"/>
    <Reference Include="DV.Common"/>
    <Reference Include="DV.Interaction"/>
    <Reference Include="DV.PointSet"/>
    <Reference Include="DV.RailTrack" />
    <Reference Include="DV.ThingTypes"/>
    <Reference Include="DV.Utils"/>
    <Reference Include="Microsoft.CSharp"/>
    <Reference Include="Newtonsoft.Json"/>
    <Reference Include="net.smkd.vector3d"/>
    <Reference Include="WorldStreamer" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule"/>
    <Reference Include="UnityEngine.IMGUIModule"/>
    <PackageReference Include="UnityModManager" Version="0.31.1"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Signals.Game"><HintPath>$(MSBuildProjectDirectory)\..\DVSignals\Signals.Game.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Signals.Common"><HintPath>$(MSBuildProjectDirectory)\..\DVSignals\Signals.Common.dll</HintPath><Private>false</Private></Reference>
    <Compile Remove="Multiplayer\**\*.cs;tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.svg"/>
    <EmbeddedResource Include="index.html"/>
    <EmbeddedResource Include="leaflet.rotatedImageOverlay.js"/>
    <EmbeddedResource Include="licenses/*.png"/>
    <EmbeddedResource Include="main.js"/>
    <EmbeddedResource Include="signal-dispatch.js"/>
    <EmbeddedResource Include="style.css"/>
  </ItemGroup>
</Project>
